version: '3'
volumes:
  db_files:
services:
  # python service - runs gunicorn
  python:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: tempBerry.settings.dev
      # DJANGO_SETTINGS_MODULE: tempBerry.settings.live
      DJANGO_ALLOWED_HOSTS: "*"
      DATABASE_URL: postgres://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME
      CACHE_URL: $CACHE_URL
    depends_on:
      - postgres
      - redis
    # uncomment the following line for development
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app/app
      - ./htdocs:/app/htdocs
    ports:
      - "8000:8000"

  # database
  postgres:
    image: postgres:10.4
    volumes:
    - ./dumps:/docker-entrypoint-initdb.d
    - db_files:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
  
  # redis cache
  redis:
    image: redis:2.8
