# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-16 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyAggregatedTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_day', models.DateField(db_index=True, verbose_name='The day where this entry is calculated for')),
                ('datetime_hour', models.IntegerField(db_index=True, verbose_name='The hour this entry is calculated for')),
                ('average_temperature', models.FloatField(null=True, verbose_name='Average Temperature')),
                ('average_humidity', models.FloatField(null=True, verbose_name='Average Humidity')),
                ('average_air_pressure', models.FloatField(null=True, verbose_name='Average Air Pressure')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.Room')),
            ],
            options={
                'ordering': ('-datetime_day', '-datetime_hour'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='hourlyaggregatedtemperature',
            unique_together=set([('room', 'datetime_day', 'datetime_hour')]),
        ),
    ]
