# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0006_room_sensor_id_mapping'),
        ('aggregatedTemperatures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlyaggregatedtemperature',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='hourlyaggregatedtemperature',
            name='average_air_pressure',
            field=models.FloatField(null=True, verbose_name='Average Air Pressure'),
        ),
        migrations.AddField(
            model_name='hourlyaggregatedtemperature',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='temperatures.Room'),
        ),
        migrations.AlterField(
            model_name='hourlyaggregatedtemperature',
            name='average_humidity',
            field=models.FloatField(null=True, verbose_name='Average Humidity'),
        ),
        migrations.AlterField(
            model_name='hourlyaggregatedtemperature',
            name='average_temperature',
            field=models.FloatField(null=True, verbose_name='Average Temperature'),
        ),
    ]
