# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0009_auto_20171221_2007'),
        ('aggregatedTemperatures', '0002_aggregates_by_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourlyaggregatedtemperature',
            options={'ordering': ('-datetime_day', '-datetime_hour')},
        ),
        migrations.AlterUniqueTogether(
            name='hourlyaggregatedtemperature',
            unique_together=set([('room', 'datetime_day', 'datetime_hour')]),
        ),
    ]
