# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregatedTemperatures', '0003_ordering_unique'),
        ('temperatures', '0011_move_room_to_smarthome'),
        ('smarthome', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyaggregatedtemperature',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.Room'),
        ),
    ]
