# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperaturedataentry',
            options={'ordering': ('sensor_id', 'created_at')},
        ),
    ]
