# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0003_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Whether this room is public or not'),
        ),
    ]
