# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-16 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSensorIdMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(db_index=True)),
                ('start_date', models.DateTimeField(verbose_name='Date time after when this mapping is valid')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date time until when this mappingi s valid')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_id_mappings', to='smarthome.Room')),
            ],
            options={
                'verbose_name': 'Mapping between room and sensor id',
                'verbose_name_plural': 'Mappings between rooms and sensor ids',
            },
        ),
        migrations.CreateModel(
            name='TemperatureDataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, verbose_name='When was this entry created at')),
                ('source', models.CharField(max_length=128, verbose_name='Where is this entry from')),
                ('sensor_id', models.IntegerField(db_index=True)),
                ('temperature', models.FloatField(null=True, verbose_name='Temeprature in Celsius')),
                ('humidity', models.FloatField(null=True, verbose_name='Relative humidify')),
                ('air_pressure', models.FloatField(null=True, verbose_name='Air pressure in PA')),
                ('battery', models.SmallIntegerField(null=True, verbose_name='Battery status of the sensor')),
                ('real_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.Sensor', verbose_name='Which sensor is this entry associated to')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.Room', verbose_name='Which room is this entry associated to')),
            ],
            options={
                'ordering': ('sensor_id', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='UnknownDataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, verbose_name='When was this entry created at')),
                ('source', models.CharField(max_length=128, verbose_name='Where is this entry from')),
                ('raw_data', models.TextField()),
                ('real_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.Sensor', verbose_name='Which sensor is this entry associated to')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.Room', verbose_name='Which room is this entry associated to')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
