# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0004_room_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('created_at',), 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='room',
            name='has_air_pressure',
            field=models.BooleanField(default=False, verbose_name='Whether this room has a working air pressure sensor'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_humidity',
            field=models.BooleanField(default=False, verbose_name='Whether this room has a working humidity sensor'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_temperature',
            field=models.BooleanField(default=False, verbose_name='Whether this room has a working temperature sensor'),
        ),
        migrations.AddField(
            model_name='temperaturedataentry',
            name='air_pressure',
            field=models.FloatField(null=True, verbose_name='Air pressure in PA'),
        ),
        migrations.AddField(
            model_name='unknowndataentry',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='temperatures.Room', verbose_name='Which room is this entry associated to'),
        ),
        migrations.AlterField(
            model_name='temperaturedataentry',
            name='battery',
            field=models.SmallIntegerField(null=True, verbose_name='Battery status of the sensor'),
        ),
        migrations.AlterField(
            model_name='temperaturedataentry',
            name='humidity',
            field=models.FloatField(null=True, verbose_name='Relative humidify'),
        ),
        migrations.AlterField(
            model_name='temperaturedataentry',
            name='temperature',
            field=models.FloatField(null=True, verbose_name='Temeprature in Celsius'),
        ),
    ]
