# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0005_air_pressure_and_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSensorIdMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(db_index=True)),
                ('start_date', models.DateTimeField(verbose_name='Date time after when this mapping is valid')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date time until when this mappingi s valid')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_id_mappings', to='temperatures.Room')),
            ],
            options={
                'verbose_name': 'Mapping between room and sensor id',
                'verbose_name_plural': 'Mappings between rooms and sensor ids',
            },
        ),
        migrations.AlterModelOptions(
            name='unknowndataentry',
            options={'ordering': ('created_at',)},
        ),
    ]
