# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0006_room_sensor_id_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_updated_at',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='When was this room last updated'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_created=True, verbose_name='When was this room created'),
        ),
    ]
