# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0007_room_last_updated_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='When was this room created'),
        ),
        migrations.AlterField(
            model_name='temperaturedataentry',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, verbose_name='When was this entry created at'),
        ),
        migrations.AlterField(
            model_name='unknowndataentry',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, verbose_name='When was this entry created at'),
        ),
    ]
