# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-06 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
        ('temperatures', '0009_auto_20171221_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='smarthome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='smarthome.SmartHome', verbose_name='Smart Home that this Room belongs to'),
        ),
    ]
