# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0010_room_smarthome'),
        ('aggregatedTemperatures', '0003_ordering_unique'),
        ('binarySensor', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # rename table for rooms to smarthome_room
                migrations.AlterModelTable('room', 'smarthome_room'),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='Room',
                ),
            ],
        ),
    ]
