# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0011_move_room_to_smarthome'),
        ('smarthome', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsensoridmapping',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_id_mappings', to='smarthome.Room'),
        ),
        migrations.AlterField(
            model_name='temperaturedataentry',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.Room', verbose_name='Which room is this entry associated to'),
        ),
        migrations.AlterField(
            model_name='unknowndataentry',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.Room', verbose_name='Which room is this entry associated to'),
        ),
    ]
