# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-06 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name of the smart home')),
                ('description', models.TextField(verbose_name='Additional information for the smart home')),
                ('address', models.CharField(max_length=256, verbose_name='Address of the smart home (e.g., used for weather information)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
