# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-06 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name of the smart home')),
                ('description', models.TextField(verbose_name='Additional information for the smart home')),
                ('address', models.CharField(max_length=256, verbose_name='Address of the smart home (e.g., used for weather information)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Smart Home',
                'verbose_name_plural': 'Smart Homes',
            },
        ),
        migrations.CreateModel(
            name='SmartHomeApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('read', 'Read only access'), ('read_write', 'Read and write access'), ('disabled', 'No access')], default='disabled', max_length=16, verbose_name='Access Type for the API Key')),
                ('key', models.CharField(default='', max_length=128, verbose_name='API Key')),
                ('smarthome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='smarthome.SmartHome', verbose_name='Smart Home that this API Key belongs to')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.AlterUniqueTogether(
            name='smarthomeapikey',
            unique_together=set([('key', 'smarthome')]),
        ),
    ]
