# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
        ('temperatures', '0011_move_room_to_smarthome'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='When was this room last updated')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='When was this room created')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the room')),
                ('comment', models.TextField(verbose_name='Comment for this room')),
                ('public', models.BooleanField(default=False, verbose_name='Whether this room is public or not')),
                ('has_temperature', models.BooleanField(default=False, verbose_name='Whether this room has a working temperature sensor')),
                ('has_humidity', models.BooleanField(default=False, verbose_name='Whether this room has a working humidity sensor')),
                ('has_air_pressure', models.BooleanField(default=False, verbose_name='Whether this room has a working air pressure sensor')),
                ('smarthome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.SmartHome', related_name='rooms', verbose_name='Smart Home that this Room belongs to')),
            ],
            options={
                'ordering': ('created_at',),
                'verbose_name_plural': 'Rooms',
                'verbose_name': 'Room',
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=state_operations,
        ),
    ]
