# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='When was this sensor config was last updated')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='When was this sensor created')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the sensor')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment for this sensor')),
                ('public', models.BooleanField(db_index=True, default=False, verbose_name='Whether this sensor is public or not')),
                ('type', models.CharField(choices=[('air_pressure', 'Air Pressure'), ('camera', 'Camera'), ('door', 'Door'), ('temperature', 'Temperature'), ('window', 'Window'), ('main_door', 'Main Door'), ('movement', 'Movement'), ('network_speed', 'Network Speed')], db_index=True, max_length=24, verbose_name='Type of the sensor')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='smarthome.Room', verbose_name='Room that this label belongs to')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'ordering': ('room', 'created_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SensorIdToSensorMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(db_index=True, verbose_name='The sensor id that the sensor is mapped to')),
                ('start_date', models.DateTimeField(verbose_name='Date time after when this mapping is valid')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date time until when this mapping is valid')),
                ('real_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_ids', to='smarthome.Sensor')),
            ],
            options={
                'verbose_name': 'Mapping between sensor and sensor id',
                'verbose_name_plural': 'Mappings between sensors and sensor ids',
            },
        ),
    ]
