# Generated by Django 2.2.12 on 2020-04-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0002_room_comment_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('air_pressure', 'Air Pressure'), ('camera', 'Camera'), ('door', 'Door'), ('temperature', 'Temperature'), ('plant', 'PLant'), ('window', 'Window'), ('main_door', 'Main Door'), ('movement', 'Movement'), ('network_speed', 'Network Speed')], db_index=True, max_length=24, verbose_name='Type of the sensor'),
        ),
    ]
