# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-16 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinarySensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, verbose_name='When was this entry created at')),
                ('source', models.CharField(max_length=128, verbose_name='Where is this entry from')),
                ('sensor_id', models.IntegerField(db_index=True)),
                ('binary_state', models.SmallIntegerField()),
                ('real_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.Sensor', verbose_name='Which sensor is this entry associated to')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.Room', verbose_name='Which room is this entry associated to')),
            ],
            options={
                'ordering': ('sensor_id', 'created_at'),
            },
        ),
    ]
