# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0003_sensor_sensoridtosensormapping'),
        ('binarySensor', '0002_fk_room_moved_to_smarthome'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarysensordata',
            name='real_sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.Sensor', verbose_name='Which sensor is this entry associated to'),
        ),
    ]
